feat(SLB-306): Info Grid
amazeeio-solutions/silverback-template pull request #226
Opened 2024-05-09 14:51 UTC by elistone

## Description of changes
Adds info grid block.

## How has this been tested?

- [ ] Manually
- [ ] Unit tests
- [ ] Integration tests

2024-05-17 06:49 UTC, Leksat requested changes
@elistone There are just two comments which indicate probable bugs. Indicated with 🐛 

The rest are nit picks 🙂

2024-05-17 06:49 UTC, Leksat commented on .idea/prettier.xml
> +    <option name="myConfigurationMode" value="MANUAL" />
What it does?

2024-05-17 06:49 UTC, Leksat commented on packages/drupal/gutenberg_blocks/src/blocks/info-grid-item.tsx
> +  },
🐛 Shouldn't it be restricted to
```ts
  parent: ['custom/info-grid'],
```
?

Currently it can be added outside of `custom/info-grid`. Which does not fit the schema.

2024-05-17 06:49 UTC, Leksat commented on packages/drupal/gutenberg_blocks/src/utils/icon-list.ts
> +  if (!iconFileName || iconFileName === '') {
`!iconFileName` equals to `iconFileName === ''`. Something else was meant here?

2024-05-17 06:49 UTC, Leksat commented on packages/schema/src/schema.graphql
> +type BlockInfoGridItem @default @value {
`BlockInfoGridItem` is never used as mandatory type, so `@default @value` can be removed.

2024-05-17 06:49 UTC, Leksat commented on packages/drupal/gutenberg_blocks/src/utils/icon-list.ts
> +// NOTE: search this file for "*" to find the places where you need to add your new icon.
I would simplify it. I think we can use TS types here in the way that no comments will be needed.

2024-05-17 06:49 UTC, Leksat commented on packages/drupal/gutenberg_blocks/src/utils/icon-list.ts
> +      label: __(defaultLabel),
This does not work because it's `Drupal.t` under the hood. It can take only literal strings. Otherwise the string won't be extracted.

2024-05-17 06:49 UTC, Leksat commented on packages/drupal/gutenberg_blocks/src/utils/icon-list.ts
> +  defaultValue: string = '',
I would try to avoid adding a lot of parameters.
```ts
limitedIconListOption([...], true, 'Default', '_none')
```
is hard to understand.

If a function really needs a lot of params, I would make it a single object, so in the end you have
```ts
limitedIconListOption({
  icons: [...],
  addDefault: true,
  defaultLabel: 'Default',
  defaultValue: '_none',
})
```

More verbose, but easier to understand.

2024-05-17 06:49 UTC, Leksat commented on packages/drupal/gutenberg_blocks/src/utils/icon-list.ts
> +  defaultValue: string = '',
At the moment the function is used with only the first arg passed. Everything else is always default.

It looks like the function is designed with future use-cases in mind. But that future might never come 😛

2024-05-17 06:49 UTC, Leksat commented on packages/drupal/gutenberg_blocks/src/blocks/info-grid-item.tsx
> +          <div className={'container-label'}>{__('Info Grid Item')}</div>
Maybe just `Item`? Looks verbose to me at the moment
![Screenshot 2024-05-16 at 15 21 21](https://github.com/AmazeeLabs/silverback-template/assets/989015/e99aeda2-f9f1-4488-9804-ef75bd90e36b)

But let Isa decided this 🙂

2024-05-17 06:49 UTC, Leksat commented on packages/drupal/gutenberg_blocks/src/blocks/info-grid-item.tsx
> +    const iconPreviewStyle = { maxWidth: '50px' };
It is used just once. Maybe inline it?

2024-05-17 06:49 UTC, Leksat commented on packages/drupal/gutenberg_blocks/src/utils/icon-list.ts
> +// NOTE: search this file for "*" to find the places where you need to add your new icon.
Actually I'm not sure if this file is needed at all. Because everything it contains is used only once, and maybe can be inlined (?)

2024-05-17 06:49 UTC, Leksat commented on packages/schema/src/schema.graphql
> +  cta: BlockCta @resolveEditorBlockChildren @seek(pos: 1)
🐛 From the grid item block source:
```tsx
          <InnerBlocks
            templateLock={false}
            allowedBlocks={['custom/heading', 'core/paragraph', 'custom/cta']}
```
This means that the block can have unlimited amount of children in any order. Tough, they are limited to 3 types.

Yet the schema here expects a fixed set of 3 blocks (2 first are grouped into 1).

I guess `templateLock` should be `true`?

2024-05-17 06:49 UTC, Leksat commented on packages/drupal/test_content/content/node/a397ca48-8fad-411e-8901-0eba2feb989c.yml
Would it be possible to revert this file and create a new node with the new block? I think this one is overloaded 🙈

2024-05-17 07:46 UTC, isara89 commented on packages/drupal/gutenberg_blocks/src/blocks/info-grid-item.tsx
> +          <div className={'container-label'}>{__('Info Grid Item')}</div>
No need to change - it's similar to `Accordion/Accordion item` :-)

2024-05-20 08:12 UTC, elistone commented on packages/drupal/gutenberg_blocks/src/blocks/info-grid-item.tsx
> +          <div className={'container-label'}>{__('Info Grid Item')}</div>
Isa happy with how it is, will keep it the same.

2024-05-20 08:23 UTC, elistone commented on .idea/prettier.xml
> +    <option name="myConfigurationMode" value="MANUAL" />
No idea, committed it by mistake I guess.

2024-05-20 08:29 UTC, elistone commented on packages/drupal/gutenberg_blocks/src/utils/icon-list.ts
> +// NOTE: search this file for "*" to find the places where you need to add your new icon.
Well my idea here is that it should be used more that once, anywhere we give options to select icons in blocks.
I already can see in the CTA buttons we give the option for arrow icons before or after text but nothing gets displayed to the user while making these changes.

Also icon selection is quite a common request for PMs, so I was trying to make a reusable and dynamic libarary just for use on the Gutenberg side.

2024-05-20 08:59 UTC, elistone commented on packages/drupal/test_content/content/node/a397ca48-8fad-411e-8901-0eba2feb989c.yml
So I can remove from here, but I noticed this file is what is used to create the tests for each block, so do we want to start adding more pages to the `blocks.sepc.ts` file?

2024-05-23 11:21 UTC, Leksat approved these changes

2024-06-07 10:07 UTC, merged