Switch schema package and gatsby-node to ESM
amazeeio-solutions/silverback-template pull request #98
Opened 2023-08-29 07:00 UTC by pmelab

## Description of changes

Transpile the schema package to ESM.
Switch `gatsby-node.ts` to `gatsby-node.mjs`.
Add typechecking for `gatsby-node.mjs`.

## Motivation and context

Typescript in Gatsby's node layer does not support ESM, which is necessary for a lot of advanced use cases (e.g. processing markdown).

## How has this been tested?

- [x] Manually
- [x] Unit tests
- [x] Integration tests

2023-08-29 07:00 UTC, pmelab commented
Current dependencies on/for this PR:
* dev
  * **PR #97** <a href="https://app.graphite.dev/github/pr/AmazeeLabs/silverback-template/97" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.svg" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #98** <a href="https://app.graphite.dev/github/pr/AmazeeLabs/silverback-template/98" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.svg" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/AmazeeLabs/silverback-template/98?utm_source=stack-comment).

2023-08-29 11:54 UTC, Leksat requested changes
All good except for `packages/schema/src/generated/index.ts` 😛

2023-08-29 12:41 UTC, Leksat approved these changes

2023-08-30 07:57 UTC, pmelab commented
### Merge Activity

* **Aug 30, 3:57 AM**: @pmelab started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/AmazeeLabs/silverback-template/98).

2023-08-30 07:59 UTC, merged